AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - test/**/*

Style/Documentation:
  Exclude:
    - test/**/*

Style/FormatStringToken:
  Exclude:
    - test/**/*

Style/FetchEnvVar:
  Enabled: false

Naming/FileName:
  Exclude:
    - "**/assets/**"

Style/ItBlockParameter:
  Enabled: false
