inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - lib/lemans/cli/templates/**/*

# Because `it`-s cool!
Style/ItBlockParameter:
  Enabled: true
